services:
  server:
    build: ./
    command: ./bin/main
    ports:
      - 8080:8080
    depends_on:
      db:
        condition: service_healthy
    environment: 
      - DB_PASSWORD=giftexpass
  
  db:
    restart: always
    image: postgres:latest
    volumes:
      - database_data:/var/lib/postgresql/data
      - ./docker_postgres_init.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql
    environment: 
      - POSTGRES_PASSWORD=giftexpass
      - POSTGRES_DB=giftex
    ports:
      - 5436:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  database_data:
    driver: local