name: test and docker build action

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go 1.15
        uses: actions/setup-go@v2
        with:
          go-version: ^1.15
        id: go

      - name: Test
        run: go test cmd/api/main.go -v

      - name: Docker build
        env:
          DOCKER_ID: gexaigor
        run: docker build . -t $DOCKER_ID/giftex:dev
