name: test and docker build & push action

on:
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go 1.15
        uses: actions/setup-go@v2
        with:
          go-version: ^1.15
        id: go
      - name: Test
        run: go test cmd/api/main.go -v
  docker-build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Docker login
        env:
          DOCKERHUB_ID: ${{secrets.DOCKERHUB_ID}} 
          DOCKERHUB_PASSWORD: ${{secrets.DOCKERHUB_PASSWORD}} 
        run: docker login -u $DOCKERHUB_ID -p $DOCKERHUB_PASSWORD
      - name: Docker build
        env:
          DOCKERHUB_ID: ${{secrets.DOCKERHUB_ID}} 
        run: docker build . -t $DOCKERHUB_ID/giftex:latest
      - name: Docker push
        env:
          DOCKERHUB_ID: ${{secrets.DOCKERHUB_ID}} 
        run: docker push $DOCKERHUB_ID/giftex:latest
